Repository AY2223S2-CS2113-T14-1/tp, pull requests merged in 2023-04, with the labels that each got.

#81 Fix CountSetsReps feature
  .gitignore
  data/workoutRecording.txt
  docs/team/guillaume-grn.md
  src/main/java/seedu/ui/Ui.java
  src/main/java/seedu/workout/WorkoutList.java
Labels: priority.High, severity.High

#83 Add list and delete feature for calorie tracker
  data/foodlist.txt
  src/main/java/seedu/calorietracker/CalorieTracker.java
  src/main/java/seedu/calorietracker/Food.java
  src/main/java/seedu/calorietracker/FoodDictionary.java
  src/main/java/seedu/calorietracker/FoodList.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/caloriecommands/DeleteCalorieCommand.java
  src/main/java/seedu/commands/caloriecommands/ListCaloriesCommand.java
  src/main/java/seedu/commands/errorcommands/IncorrectSyntaxCommand.java
  src/main/java/seedu/commands/errorcommands/InvalidCommand.java
  src/main/java/seedu/commands/workoutcommands/StartWorkoutCommand.java
  src/main/java/seedu/parser/CalorieParser.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/parser/WorkoutParser.java
  src/main/java/seedu/storage/CalorieTrackerStorage.java
  src/main/java/seedu/storage/FoodDictionaryStorage.java
Labels: type.Story, type.Enhancement, priority.High

#93 Add jUnit tests for Calorie and Workout Parser
  src/main/java/seedu/parser/CalorieParser.java
  src/main/java/seedu/parser/CheckCaloriesInput.java
  src/main/java/seedu/parser/WorkoutParser.java
  src/test/java/seedu/parser/CalorieParserTest.java
  src/test/java/seedu/parser/WorkoutParserTest.java
Labels: type.Task, priority.Medium

#97 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddExerciseCommandDiagram.puml
  docs/diagrams/AddExerciseDiagram.puml
  docs/diagrams/CountSetsRepsDiagram.puml
  docs/diagrams/ExitCommandDiagram.puml
  docs/diagrams/StartWorkoutCommandDiagram.puml
  docs/images/AddExerciseCommandDiagram.png
  docs/images/AddExerciseDiagram.png
  docs/images/ExitCommandDiagram.png
  docs/images/StartWorkoutCommandDiagram.png
  src/main/java/seedu/Duke.java
  src/main/java/seedu/calorietracker/CalorieTracker.java
  src/main/java/seedu/commands/caloriecommands/DeleteCalorieCommand.java
  src/main/java/seedu/commands/workoutcommands/EndWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/ListWorkoutCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/parser/WorkoutParser.java
  src/main/java/seedu/workout/Workout.java
  src/test/java/seedu/parser/ParserTest.java
Labels: type.Task, priority.High
