Repository AY2223S2-CS2113-T14-1/tp, pull requests merged in 2023-03, with the labels that each got.

#14 Add RemoveWorkout test
  src/test/java/seedu/workout/WorkoutListTest.java
Labels: priority.High

#15 Add AddCommandTest
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/workout/Workout.java
  src/test/java/seedu/commands/AddCommandTest.java
Labels: type.Task, priority.Medium

#18 Add user guide
  docs/AboutUs.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#13 Add assertion
  docs/DeveloperGuide.md
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/workout/WorkoutList.java
  src/test/java/seedu/command/ListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/workout/WorkoutTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#9 Added View Function
  build.gradle
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/ViewCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/Ui.java
  src/main/java/seedu/workout/Workout.java
  src/main/java/seedu/workout/WorkoutList.java
Labels: type.Task, priority.High

#21 DG : Add deletion mechanism description
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.Task

#22 Add developer guide for add feature
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddExerciseDiagram.puml
  docs/images/AddExerciseDiagram.png
Labels: type.Task

#31 Add view calorie feature & add exceptions
  src/main/java/seedu/calorietracker/CalorieTracker.java
  src/main/java/seedu/calorietracker/FoodList.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/IncorrectCommand.java
  src/main/java/seedu/commands/IncorrectSyntaxCommand.java
  src/main/java/seedu/commands/InvalidCommand.java
  src/main/java/seedu/commands/caloriecommands/AddCalorieCommand.java
  src/main/java/seedu/commands/caloriecommands/ViewCaloriesCommand.java
  src/main/java/seedu/commands/countcommands/CountSetsRepsCommand.java
  src/main/java/seedu/commands/workoutcommands/AddWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/DeleteWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/EndWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/HelpWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/ListWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/StartWorkoutCommand.java
  src/main/java/seedu/commands/workoutcommands/ViewWorkoutCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/exceptions/InvalidSyntaxException.java
  src/main/java/seedu/parser/CheckCaloriesInput.java
  src/main/java/seedu/parser/CheckInputs.java
  src/main/java/seedu/parser/DateFormat.java
  src/main/java/seedu/parser/DateFormatter.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/Ui.java
  src/main/java/seedu/workout/Exercise.java
  src/main/java/seedu/workout/Workout.java
  src/main/java/seedu/workout/WorkoutList.java
  src/test/java/seedu/commands/workoutcommands/AddWorkoutCommandTest.java
  src/test/java/seedu/commands/workoutcommands/DeleteCommandTest.java
  src/test/java/seedu/commands/workoutcommands/ListWorkoutCommandTest.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/workout/ExerciseTest.java
  src/test/java/seedu/workout/WorkoutListTest.java
  src/test/java/seedu/workout/WorkoutTest.java
Labels: priority.High

#34 DG : Add Delete sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteWorkoutDiagram.puml
  docs/images/DeleteWorkoutDiagram.png
Labels: type.Task, priority.Medium

#33 Updated VIew DG and UG
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/ViewDiagram.puml
  docs/images/ViewDiagram.png
  src/main/java/seedu/parser/CheckInputs.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/workout/WorkoutViewTest.java
Labels: type.Task, priority.Medium

#35 Update user guide for v2.0
  docs/UserGuide.md
  src/main/java/seedu/workout/WorkoutList.java
  src/test/java/seedu/workout/WorkoutListTest.java
Labels: type.Task, priority.High
